image: conda/miniconda3

conda_build:
  stage: build
  script:
    - apt update
    - apt install libc6 -y
    - conda install conda-build git
    - mkdir conda-bld
    - conda build ./pkg/recipe/ -c morpheme -c conda-forge --output-folder conda-bld/
  artifacts:
    paths:
      - conda-bld
  tags:
    - ci.inria.fr
    - medium
  only:
    - master
    - /release/

anaconda_master :
  stage: deploy
  script:
  - conda update --all
  - conda install conda-build anaconda-client
  - conda convert -p osx-64 conda-bld/linux-64/astec-* --output-dir conda-bld/
  - conda convert -p osx-arm64 conda-bld/linux-64/astec-* --output-dir conda-bld/
  - anaconda --token=$ANACONDA_TOKEN upload conda-bld/linux-64/astec-* --force --user morpheme
  - anaconda --token=$ANACONDA_TOKEN upload conda-bld/osx-64/astec-* --force --user morpheme
  - anaconda --token=$ANACONDA_TOKEN upload conda-bld/osx-arm64/astec-* --force --user morpheme
  retry:
    max: 2
    when: runner_system_failure
  dependencies:
    - conda_build
  tags:
    - ci.inria.fr
    - medium
  only:
  - master

pages:
  stage: deploy
  script:
  - conda env create -f ./pkg/env/astec-dev.yaml
  - source activate astec-dev
  - conda install make
  - python -m pip install .
  - cd doc
  - make clean && make html
  - mv build/html ../public
  retry:
    max: 2
    when: runner_system_failure
  artifacts:
    expire_in: 1 hour
    paths:
    - public
  dependencies: []
  tags:
    - ci.inria.fr
    - medium
  rules:
      - if: $CI_COMMIT_BRANCH =~ /^feature/
        when: manual
      - if: '$CI_COMMIT_BRANCH == "develop"'
        when: manual
      - if: '$CI_COMMIT_BRANCH == "master"'
        when: on_success

