package:
  name: astec
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'default') }}

source:
  path: ../../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)}}

about:
  home: https://astec.gitlabpages.inria.fr/astec
  license: GPL
  license_file: ../../LICENSE.txt
  summary: ASTEC package
  dev_url: https://gitlab.inria.fr/astec/astec

requirements:
  build:
    - setuptools
    - python  {{ python }}
  run:
    - vt
    - python
    - numpy
    - scipy
    - h5py
    - nibabel
    - tifffile
    - matplotlib
    - networkx
    - ipython

test:
  imports:
    - astec
